services:
  sn.request.listener:
    class: SN\RequestParamBundle\EventListener\RequestListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller }
  sn.exception.listener:
    class: SN\RequestParamBundle\EventListener\ExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
