language: php

php:
  - 7.0
  - 7.1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - $HOME/.ccache
    - $HOME/.composer/cache
  
before_script:
  - composer update --prefer-source
  - cp phpunit.xml.dist phpunit.xml

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit
  - ls build/logs

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
    slack:
        rooms:
            - sonntagnacht:CZvguyxyM0tlb6Smj7amHjTw#internetz
